feat(base repo): update base, fix bugs, add core modules
visitscotland/nuxt-bloomreach-sdk-starter pull request #4
Opened 2024-12-18 10:24 UTC by mjpvs

Hey @duncansanderson @jameshaddrillvs  , I'm interested in your thoughts about this one. When I first set up the starter repo I thought we might want to make multiple different kinds of site with it so I made it very minimal, just handling all the stuff that actually talks to the resourceapi and making sure that it could load the component library, but as the design system matures it feels like they're likely to be relatively close to each other, at least in the core. Setting up the visitscotland.com front end repo I had to pull in a bunch of this stuff from BE and BSH and fix a few bugs + version issues which we'd already done in several other sites, to get to the same point that we had already got to with BSH and with BE.

Do you think we should just put all of this into the starter, and assume that any future site will either be happy to have all of it, or can easily redact it, or do you think there's a particular sub-set of this that's worth having in here?

2024-12-18 11:32 UTC, jameshaddrillvs commented
I'm happy to bring extra stuff in if we feel it will be re-used. The more re-use the better!

If a reason to remove things arises, we can review again at that point.

2024-12-18 11:33 UTC, jameshaddrillvs approved these changes

2025-01-03 11:04 UTC, duncansanderson commented
I think all of this is good to have in the starter, most of it will be used across all of our sites and they can easily be modified/removed from a site if required.

2025-01-03 11:10 UTC, duncansanderson requested changes

2025-01-03 11:10 UTC, duncansanderson commented on components/Modules/VsBrListLinksModule.vue
Can this file be renamed to `VsBrMegalinksLinkListModule.vue` to avoid a clash with the LinkList component?

2025-01-03 11:10 UTC, duncansanderson commented on components/Modules/VsBrMultiImageLinksModule.vue
Can this file be renamed to `VsBrMegalinksMultiImageModule.vue` for consistency with other Megalink modules?

2025-01-03 11:10 UTC, duncansanderson commented on components/Modules/VsBrSingleImageLinksModule.vue
Can this file be renamed to `VsBrMegalinksSingleImageModule.vue` for consistency with other Megalink modules?

2025-01-06 15:17 UTC, merged